import { Locale } from 'react-intl'

const enUS: Locale = {
	locale: 'enUS',
	fields: {
		Username: 'Username',
		Password: 'Password',
		LogIn: 'Log In',
		LogOut: 'Log Out',

		CountNotify: 'You have {itemsCount} notifications',
		CountTasks: 'You have {itemsCount} pending tasks',
		Task: 'Task',
		ViewAllTasks: 'View all tasks',
		Settings: 'Setting',
		Account: 'Account',

		Home: 'Home',
		Statistics: 'Statistics',
		Action: 'Action',
		Day: 'Day',
		Month: 'Month',
		Year: 'Year',

		Theme: 'Theme',
		Colors: 'Colors',
		ThemeColors: 'Theme Colors',
		AdditionalColors: 'Additional Colors',
		Typography: 'Typography',
		Components: 'Components',
		Breadcrumbs: 'Breadcrumbs',
		Cards: 'Cards',
		Base: 'Base',
		Carousels: 'Carousels',
		Collapses: 'Collapses',
		Dropdowns: 'Dropdowns',
		Jumbotrons: 'Jumbotrons',
		ListGroups: 'ListGroups',
		Navs: 'Navs',
		Paginations: 'Paginations',
		Popovers: 'Popovers',
		ProgressBar: 'Progress Bar',
		Switches: 'Switches',
		Tabs: 'Tabs',
		Tooltips: 'Tooltips',
		Buttons: 'Buttons',
		ButtonDropdowns: 'ButtonDropdowns',
		ButtonGroups: 'Button Groups',
		LoadingButtons: 'Loading Buttons',
		SocialButtons: 'Social Buttons',
		Charts: 'Charts',
		Editors: 'Editors',
		TextEditors: 'Text Editors',
		CodeEditors: 'Code Editors',
		Forms: 'Forms',
		BasicForms: 'Basic Forms',
		AdvancedForms: 'Advanced Forms',

		GoogleMaps: 'Google Maps',
		DistrictXitun: 'Xitun District',
		DistrictNantun: 'Nantun District',

		Icons: 'Icons',
		FontAwesome: 'Font Awesome',
		SimpleLineIcons: 'Simple Line Icons',
		Notifications: 'Notifications',
		Alerts: 'Alerts',
		Badges: 'Badges',
		Modals: 'Modals',
		Toastr: 'Toastr',
		Plugins: 'Plugins',
		Calendar: 'Calendar',
		Spinners: 'Spinners',
		Tables: 'Tables',
		DataTable: 'Data Table',
		Widgets: 'Widgets',
		Extras: 'Extras',
		Pages: 'Pages',
		Error404: 'Error 404',
		Error500: 'Error 500',
		UIKits: 'UI Kits',
		Invoicing: 'Invoicing',
		Invoice: 'Invoice',
		Email: 'Email',
		Inbox: 'Inbox',
		Message: 'Message',
		Compose: 'Compose',
		Labels: 'Labels',
		LabelDanger: 'Label Danger',
		LabelInfo: 'Label Info',
		LabelWarning: 'Label Warning',
	},
	pluralRuleFunction(e, t) {
		return t && e === 1 ? 'one' : 'other'
	},
}

export default enUS
