import { Locale } from 'react-intl'

const zhCN: Locale = {
	locale: 'zhCN',
	fields: {
		Username: '用户名',
		Password: '密码',
		LogIn: '登入',
		LogOut: '登出',

		CountNotify: '您有 {itemsCount} 则通知',
		CountTasks: '您有 {itemsCount} 项任务',
		Task: '任务',
		ViewAllTasks: '浏览全部任务',
		Settings: '设定',
		Account: '帐户',

		Home: '首页',
		Statistics: '统计',
		Action: '操作项',
		Day: '日',
		Month: '月',
		Year: '年',

		Theme: '主题',
		Colors: '色彩',
		ThemeColors: '主题色彩',
		AdditionalColors: '额外色彩',
		Typography: '活版印刷',
		Components: '元件',
		Breadcrumbs: '面包屑',
		Cards: '卡片',
		Base: '基本',
		Carousels: '轮播',
		Collapses: '折迭',
		Dropdowns: '下拉选单',
		Jumbotrons: '广告大屏幕',
		ListGroups: '列表群组',
		Navs: '导航',
		Paginations: '分页',
		Popovers: '弹出提示窗',
		ProgressBar: '进度条',
		Switches: '开关',
		Tabs: '分页标签',
		Tooltips: '工具提示',
		Buttons: '按钮',
		ButtonDropdowns: '下拉选单按钮',
		ButtonGroups: '群组按钮',
		LoadingButtons: '读取按钮',
		SocialButtons: '社交按钮',
		Charts: '图表',
		Editors: '编辑器',
		TextEditors: '文字编辑器',
		CodeEditors: '代码编辑器',
		Forms: '表单',
		BasicForms: '基础表单',
		AdvancedForms: '进阶表单',

		GoogleMaps: '谷歌地图',
		DistrictXitun: '西屯区',
		DistrictNantun: '南屯区',

		Icons: '图示',
		FontAwesome: 'Font Awesome',
		SimpleLineIcons: 'Simple Line Icons',
		Notifications: '通知',
		Alerts: '警报',
		Badges: '徽章',
		Modals: '互动视窗',
		Toastr: '简单提示讯息',
		Plugins: '插件',
		Calendar: '日历',
		Spinners: '旋转',
		Tables: '表格',
		DataTable: '资料表格',
		Widgets: '小工具',
		Extras: '附加功能',
		Pages: '页面',
		Error404: '错误404',
		Error500: '错误500',
		UIKits: 'UI套件',
		Invoicing: '进销存',
		Invoice: '发票',
		Email: '电子邮件',
		Inbox: '收件夹',
		Message: '讯息',
		Compose: '撰写',
		Labels: '标签',
		LabelDanger: '危险',
		LabelInfo: '资讯',
		LabelWarning: '警告',
	},
	pluralRuleFunction(e, t) {
		return t && e === 1 ? 'one' : 'other'
	},
}

export default zhCN
