import { Locale } from 'react-intl'

const zhTW: Locale = {
	locale: 'zhTW',
	fields: {
		Username: '帳號',
		Password: '密碼',
		LogIn: '登入',
		LogOut: '登出',

		CountNotify: '您有 {itemsCount} 則通知',
		CountTasks: '您有 {itemsCount} 項任務',
		Task: '任務',
		ViewAllTasks: '瀏覽全部任務',
		Settings: '設定',
		Account: '帳號',

		Home: '首頁',
		Statistics: '統計',
		Action: '控制項',
		Day: '日',
		Month: '月',
		Year: '年',

		Theme: '主題',
		Colors: '色彩',
		ThemeColors: '主題色彩',
		AdditionalColors: '額外色彩',
		Typography: '活版印刷',
		Components: '元件',
		Breadcrumbs: '麵包屑',
		Cards: '卡片',
		Base: '基本',
		Carousels: '輪播',
		Collapses: '折疊',
		Dropdowns: '下拉選單',
		Jumbotrons: '廣告大屏幕',
		ListGroups: '列表群組',
		Navs: '導航',
		Paginations: '分頁',
		Popovers: '彈出提示框',
		ProgressBar: '進度條',
		Switches: '開關',
		Tabs: '分頁標籤',
		Tooltips: '工具提示',
		Buttons: '按鈕',
		ButtonDropdowns: '下拉選單按鈕',
		ButtonGroups: '群組按鈕',
		LoadingButtons: '讀取按鈕',
		SocialButtons: '社交按鈕',
		Charts: '圖表',
		Editors: '編輯器',
		TextEditors: '文字編輯器',
		CodeEditors: '代碼編輯器',
		Forms: '表單',
		BasicForms: '基礎表單',
		AdvancedForms: '進階表單',

		GoogleMaps: '谷歌地圖',
		DistrictXitun: '西屯區',
		DistrictNantun: '南屯區',

		Icons: '圖示',
		FontAwesome: 'Font Awesome',
		SimpleLineIcons: 'Simple Line Icons',
		Notifications: '通知',
		Alerts: '警報',
		Badges: '徽章',
		Modals: '互動視窗',
		Toastr: '簡單提示訊息',
		Plugins: '插件',
		Calendar: '日曆',
		Spinners: '旋轉',
		Tables: '表格',
		DataTable: '資料表格',
		Widgets: '小工具',
		Extras: '附加功能',
		Pages: '頁面',
		Error404: '錯誤404',
		Error500: '錯誤500',
		UIKits: 'UI套件',
		Invoicing: '進銷存',
		Invoice: '發票',
		Email: '電子郵件',
		Inbox: '收件夾',
		Message: '訊息',
		Compose: '撰寫',
		Labels: '標籤',
		LabelDanger: '危險',
		LabelInfo: '資訊',
		LabelWarning: '警告',
	},
	pluralRuleFunction(e, t) {
		return t && e === 1 ? 'one' : 'other'
	},
}

export default zhTW
