interface IRoutes {
	[uri: string]: string
}

const routes: IRoutes = {
	'/': 'Home',
	'/theme/colors': 'Colors',
	'/theme/typography': 'Typography',
	'/base/breadcrumbs': 'Breadcrumbs',
	'/base/cards': 'Cards',
	'/base/carousels': 'Carousels',
	'/base/collapses': 'Collapses',
	'/base/dropdowns': 'Dropdowns',
	'/base/jumbotrons': 'Jumbotrons',
	'/base/list-groups': 'ListGroups',
	'/base/navs': 'Navs',
	'/base/paginations': 'Paginations',
	'/base/popovers': 'Popovers',
	'/base/progress-bar': 'ProgressBar',
	'/base/switches': 'Switches',
	'/base/tabs': 'Tabs',
	'/base/tooltips': 'Tooltips',
	'/buttons/buttons': 'Buttons',
	'/buttons/button-dropdowns': 'ButtonDropdowns',
	'/buttons/button-groups': 'ButtonGroups',
	'/buttons/loading-buttons': 'LoadingButtons',
	'/buttons/social-buttons': 'SocialButtons',
	'/charts': 'Charts',
	'/editors/text-editors': 'TextEditors',
	'/editors/code-editors': 'CodeEditors',
	'/forms/basic-forms': 'BasicForms',
	'/forms/advanced-forms': 'AdvancedForms',
	'/google-maps': 'GoogleMaps',
	'/icons/font-awesome': 'FontAwesome',
	'/icons/simple-line-icons': 'SimpleLineIcons',
	'/notifications/alerts': 'Alerts',
	'/notifications/badges': 'Badges',
	'/notifications/modals': 'Modals',
	'/notifications/toastr': 'Toastr',
	'/plugins/calendar': 'Calendar',
	'/plugins/spinners': 'Spinners',
	'/tables/datatable': 'DataTable',
	'/tables/tables': 'Tables',
	'/widgets': 'Widgets',
	'/ui-kits/invoicing/invoice': 'Invoice',
	'/ui-kits/email/compose': 'Compose',
	'/ui-kits/email/inbox': 'Inbox',
	'/ui-kits/email/message': 'Message',
}
export default routes
